2021-11-07 00:55:03,213 INFO    MainThread:41853 [internal.py:wandb_internal():87] W&B internal server running at pid: 41853, started at: 2021-11-07 00:55:03.213248
2021-11-07 00:55:03,214 DEBUG   HandlerThread:41853 [handler.py:handle_request():130] handle_request: run_start
2021-11-07 00:55:03,215 INFO    WriterThread:41853 [datastore.py:open_for_write():77] open: /home/cx/rmvision/yolov5-RM/wandb/offline-run-20211107_005502-12snnij8/run-12snnij8.wandb
2021-11-07 00:55:03,216 DEBUG   HandlerThread:41853 [meta.py:__init__():40] meta init
2021-11-07 00:55:03,216 DEBUG   HandlerThread:41853 [meta.py:__init__():54] meta init done
2021-11-07 00:55:03,216 DEBUG   HandlerThread:41853 [meta.py:probe():214] probe
2021-11-07 00:55:03,222 DEBUG   HandlerThread:41853 [git.py:repo():33] git repository is invalid
2021-11-07 00:55:03,223 DEBUG   HandlerThread:41853 [meta.py:_save_pip():58] save pip
2021-11-07 00:55:03,224 DEBUG   HandlerThread:41853 [meta.py:_save_pip():72] save pip done
2021-11-07 00:55:03,224 DEBUG   HandlerThread:41853 [meta.py:_save_conda():79] save conda
2021-11-07 00:55:04,167 DEBUG   HandlerThread:41853 [meta.py:_save_conda():89] save conda done
2021-11-07 00:55:04,167 DEBUG   HandlerThread:41853 [meta.py:probe():252] probe done
2021-11-07 00:55:05,741 DEBUG   HandlerThread:41853 [handler.py:handle_request():130] handle_request: shutdown
2021-11-07 00:55:05,741 INFO    HandlerThread:41853 [handler.py:finish():731] shutting down handler
2021-11-07 00:55:05,741 INFO    WriterThread:41853 [datastore.py:close():281] close: /home/cx/rmvision/yolov5-RM/wandb/offline-run-20211107_005502-12snnij8/run-12snnij8.wandb
2021-11-07 00:55:06,215 INFO    SenderThread:41853 [sender.py:finish():1091] shutting down sender
2021-11-07 00:55:06,219 INFO    MainThread:41853 [internal.py:handle_exit():77] Internal process exited
